### ISSUE TITLE
Similar art

### ISSUE THREAD

**Issue by konklone** [seanherron/Flag-Webicons#4]
No actionables here! Just noticed this repository and wanted to leave a note - I did something similar over at [isitchristmas/flags](https://github.com/isitchristmas/flags), but it's all PNGs scraped from Flagpedia, and I was much more reckless about copyright issues.

**Comment by seanherron** [comment]
Nice! I created this when I was still at my old job, had to be very sensitive about the source and what was included as it was going on a .gov site.
